# Generated by Django 3.1.6 on 2021-02-07 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promotion_type', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('effective_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
